spring:
  application:
    name: auth-service
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES:localhost:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/prod}
    publisher-confirm-type: correlated   # async ACK/NACK from broker

jwt:
  secret: ${JWT_SECRET:practice-secret-key-must-be-at-least-256-bits-long}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}  # 24 hours

auth:
  email-verification:
    expiration-hours: 48
  producer:
    user-registered:
      exchange:    auth.exchange
      routing-key: user.registered
